---
title: "Analysis"
---

Loading necessary libraries :

```{r}
#| warning: false
#| code-fold: true
#| code-summary: "Show the code"
library(readxl)
library(ggplot2)
library(tidyverse)
library(dplyr)
```

Load the data:

```{r}
#| code-fold: true
#| code-summary: "Show the code"
load("library_museum_updated.RData")
data <-library_museum_updated
```

Correlation between population and the number of books in the library

```{r}
#| code-fold: true
#| code-summary: "Show the code"
# Veri türlerini düzelt
data$population <- as.numeric(data$population)
data$book_num <- as.numeric(data$book_num)


# Korelasyon hesapla
cor_pop_book <- cor(data$population, data$book_num)
cat("Correlation between Population and Number of Books:",cor_pop_book,"\n")
```

Plot

```{r}
#| code-fold: true
#| code-summary: "Show the code"
ggplot(data, aes(x = population, y = book_num)) +
  geom_point(color = "purple") +  
  geom_smooth(method = "lm", se = FALSE, color = "yellow", formula = y ~ x)+ 
  labs(x = "Population", y = "Book Count") + 
  ggtitle("Scatter Plot of Population vs Book Count") +
  theme_minimal() +
  theme(plot.title = element_text(size = 12, hjust = 0.5),axis.text.x = element_text(angle = 45, hjust = 1, size = 6)) +
  scale_x_continuous(labels = scales::comma, breaks = seq(0, 15000000, by = 1000000))
```

```{r}
#| code-fold: true
#| code-summary: "Show the code"
data |>
  filter(year==2022) |>
  mutate(book_per_person=book_num/population) |>
  ggplot(aes(x = city, y = book_per_person*100)) +
  geom_point(color = "purple") +  
  geom_smooth(method = "lm", se = FALSE, color = "yellow", formula = y ~ x) + 
  labs(x = "Cities", y = "Book Number Per Population(*100)") + 
  ggtitle("Scatter Plot of Cities vs Book Number Per Population") +
  theme_minimal() +
  theme(plot.title = element_text(size = 12, hjust = 0.5),axis.text.x = element_text(angle = 90, hjust = 1, size = 6)) 

```

```{r}
#| code-fold: true
#| code-summary: "Show the code"
data |>
  filter(year==2022) |>
  mutate(museum_per_person=(ministry_museum_num + private_museum_num)/population) |>
  ggplot(aes(x = city, y = museum_per_person*100000)) +
  geom_point(color = "purple") +  
  geom_smooth(method = "lm", se = FALSE, color = "yellow", formula = y ~ x) + 
  labs(x = "Cities", y = "Museum Number Per Population(*100000)") + 
  ggtitle("Scatter Plot of Cities vs Museum Number Per Population") +
  theme_minimal() +
  theme(plot.title = element_text(size = 12, hjust = 0.5),axis.text.x = element_text(angle = 90, hjust = 1, size = 6)) 

```
