---
title: "Team Synergy"
sidebar: false 
---

Welcome! This is our project webpage.

Please stay tuned to follow our project activities.

# Team Members

1.  [Beyza Göktaş](https://emu-hacettepe-analytics.github.io/emu430-fall2023-beyzagoktas/)

2.  [Emre Gül](https://emu-hacettepe-analytics.github.io/emu430-fall2023-emregul57/)

3.  [Hatice Nur Güneş](https://emu-hacettepe-analytics.github.io/emu430-fall2023-haticenurgunes/)

4.  [Kerem Kaplan](https://emu-hacettepe-analytics.github.io/emu430-fall2023-keremkpln/)

5.  [Osman Bolat](https://emu-hacettepe-analytics.github.io/emu430-fall2023-OsmanBOLAT/)

# Project Topic
In our project, we will use a data set containing statistics of museums and libraries in different cities of Turkey. This data set includes values such as the number of libraries in the cities, the number of museums, the number of people registered in the library, and the number of visitors in museums. Thanks to these rich data sets, it is possible to obtain important values such as the average number of visitors and the number of books.

In addition, by working on the cultural values of cities according to years, average, maximum, etc. we can determine the values. These analyzes will help us understand the use of cultural institutions in each city and the balances between demand and provision. The resulting results will guide us in determining the demands for cultural services, identifying deficiencies and highlighting areas that require further development.

# Data Set
